name: CI

on: [pull_request, push]

jobs:
  build:
    
    name: Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 21.3
            elixir: 1.10.4
          - otp: 23.2.1
            elixir: 1.11.3
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '${{matrix.elixir}}'
        otp-version: '${{matrix.otp}}'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{runner.os}}-mix-${{hashFiles('**/mix.lock')}}
        restore-keys: ${{runner.os}}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
